### ISSUE TITLE
PR

### ISSUE THREAD

**Issue by yanndegat** [cdemers/journald2graylog#1]
The following changes since commit 023d493104034c985e5ef7c01bf4ff01dcbdd6cc:

  Add journald2graylog docker container (2016-06-23 13:20:57 +0200)

are available in the git repository at:

  git@gitlab.com:/yanndegat/journald2graylog.git master

for you to fetch changes up to 023d493104034c985e5ef7c01bf4ff01dcbdd6cc:

  Add journald2graylog docker container (2016-06-23 13:20:57 +0200)

**Comment by cdemers** [comment]
Thanks a lot, I will have a look asap.

**Comment by cdemers** [comment]
I think our code have evolved in different ways, but thanks a lot for sharing your contribution!
